addons:
  ssh_known_hosts: russellhay.com
language: go
go:
- tip
install:
- go get -u -v github.com/kardianos/govendor
- go get -u -v github.com/spf13/hugo
- cd $GOPATH/src/github.com/spf13/hugo && govendor sync && go install
script:
- cd $GOPATH/src/github.com/poorimpulse/cord
- hugo
before_install:
- openssl aes-256-cbc -K $encrypted_6667da90b700_key -iv $encrypted_6667da90b700_iv
  -in deploy.rsa.enc -out deploy.rsa -d
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy.rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy.rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --quiet $TRAVIS_BUILD_DIR/public/ deploy@russellhay.com:/home/www/cordcarney/
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: rsync -r --quiet $TRAVIS_BUILD_DIR/public/ deploy@russellhay.com:/home/www/cordcarney.beta/
    on:
      branch: development
