# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Portfolio"
license = "MIT"
licenselink = "https://github.com/poorimpulse/cord/blob/master/themes/portfolio/LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = []
features = []
min_version = "0.20"

[author]
  name = "Russell Hay"
  homepage = "https://russellhay.com"

